POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "johndoe12",
  "name": "John Doe",
  "email": "johndoe@mail.com",
  "password": "Password123@",
  "phone_number": "081234567890",
  "role_id": "ca3489a1-6e46-4377-811e-a314bf4ec5c0"
}